export const apiCategories = [
  { name: "AI & Machine Learning", slug: "ai-ml", count: 156, icon: "Brain" },
  { name: "Payment Processing", slug: "payments", count: 89, icon: "CreditCard" },
  { name: "Data & Analytics", slug: "data", count: 124, icon: "BarChart3" },
  { name: "Communication", slug: "communication", count: 67, icon: "MessageSquare" },
  { name: "Maps & Location", slug: "maps", count: 45, icon: "MapPin" },
  { name: "Weather", slug: "weather", count: 23, icon: "Cloud" },
  { name: "Finance", slug: "finance", count: 98, icon: "TrendingUp" },
  { name: "Social Media", slug: "social", count: 54, icon: "Share2" },
  { name: "Authentication", slug: "auth", count: 31, icon: "Shield" },
  { name: "Storage & Files", slug: "storage", count: 42, icon: "HardDrive" },
]

export const popularApis = [
  {
    id: "openai-gpt",
    name: "OpenAI GPT-4",
    provider: "OpenAI",
    description: "Advanced language model for text generation, analysis, and conversation.",
    category: "AI & Machine Learning",
    rating: 4.9,
    users: 45200,
    latency: "230ms",
    uptime: "99.98%",
    pricing: "From $0.03/1K tokens",
    tags: ["AI", "NLP", "Text Generation"],
    featured: true,
  },
  {
    id: "stripe-payments",
    name: "Stripe Payments",
    provider: "Stripe",
    description: "Complete payment processing platform with support for 135+ currencies.",
    category: "Payment Processing",
    rating: 4.8,
    users: 38100,
    latency: "145ms",
    uptime: "99.99%",
    pricing: "From $0.01/request",
    tags: ["Payments", "E-commerce", "Subscriptions"],
    featured: true,
  },
  {
    id: "twilio-sms",
    name: "Twilio Messaging",
    provider: "Twilio",
    description: "Send and receive SMS, MMS, and WhatsApp messages at scale globally.",
    category: "Communication",
    rating: 4.7,
    users: 29400,
    latency: "180ms",
    uptime: "99.95%",
    pricing: "From $0.0075/message",
    tags: ["SMS", "Messaging", "WhatsApp"],
    featured: false,
  },
  {
    id: "google-maps",
    name: "Google Maps Platform",
    provider: "Google",
    description: "Maps, routes, and places APIs for location-based experiences.",
    category: "Maps & Location",
    rating: 4.8,
    users: 52300,
    latency: "120ms",
    uptime: "99.99%",
    pricing: "From $0.005/request",
    tags: ["Maps", "Geocoding", "Directions"],
    featured: true,
  },
  {
    id: "aws-rekognition",
    name: "AWS Rekognition",
    provider: "Amazon",
    description: "Image and video analysis using deep learning for object and face detection.",
    category: "AI & Machine Learning",
    rating: 4.6,
    users: 18700,
    latency: "340ms",
    uptime: "99.97%",
    pricing: "From $0.001/image",
    tags: ["Computer Vision", "Image Analysis", "AI"],
    featured: false,
  },
  {
    id: "sendgrid-email",
    name: "SendGrid Email",
    provider: "Twilio",
    description: "Reliable email delivery service with analytics and template management.",
    category: "Communication",
    rating: 4.5,
    users: 24600,
    latency: "95ms",
    uptime: "99.95%",
    pricing: "Free tier available",
    tags: ["Email", "Transactional", "Marketing"],
    featured: false,
  },
  {
    id: "plaid-finance",
    name: "Plaid Financial",
    provider: "Plaid",
    description: "Connect with user bank accounts for payments, balance, and transaction data.",
    category: "Finance",
    rating: 4.7,
    users: 15800,
    latency: "210ms",
    uptime: "99.96%",
    pricing: "From $0.30/connection",
    tags: ["Banking", "Finance", "Transactions"],
    featured: true,
  },
  {
    id: "cloudinary-media",
    name: "Cloudinary Media",
    provider: "Cloudinary",
    description: "Image and video management, optimization, and transformation at scale.",
    category: "Storage & Files",
    rating: 4.6,
    users: 21300,
    latency: "85ms",
    uptime: "99.98%",
    pricing: "Free tier available",
    tags: ["Media", "Images", "CDN"],
    featured: false,
  },
]

export const testimonials = [
  {
    name: "Sarah Chen",
    role: "CTO",
    company: "NexaTech",
    quote: "APIFlow transformed our development workflow. We integrated 5 APIs in a single afternoon that would have taken weeks to evaluate and set up individually.",
    rating: 5,
  },
  {
    name: "Marcus Johnson",
    role: "Lead Developer",
    company: "BuildStack",
    quote: "The documentation quality and interactive playground are unmatched. Best API marketplace I've used in my 12 years of development.",
    rating: 5,
  },
  {
    name: "Elena Rodriguez",
    role: "VP of Engineering",
    company: "DataStream",
    quote: "Consolidated our API spending by 40% after switching to APIFlow. The analytics dashboard alone is worth the subscription.",
    rating: 5,
  },
]

export const pricingTiers = [
  {
    name: "Free",
    tagline: "For side projects and exploration",
    price: { monthly: 0, annual: 0 },
    features: [
      "1,000 API calls/month",
      "5 API integrations",
      "Community support",
      "Basic analytics",
      "API playground access",
    ],
    limitations: ["No SLA guarantee", "Rate limited to 10 req/sec"],
    cta: "Start Free",
    popular: false,
  },
  {
    name: "Starter",
    tagline: "For growing applications",
    price: { monthly: 29, annual: 24 },
    features: [
      "50,000 API calls/month",
      "25 API integrations",
      "Email support (24h)",
      "Advanced analytics",
      "API playground access",
      "Webhook support",
      "Custom API keys",
    ],
    limitations: ["Rate limited to 100 req/sec"],
    cta: "Start Trial",
    popular: false,
  },
  {
    name: "Pro",
    tagline: "For production workloads",
    price: { monthly: 99, annual: 79 },
    features: [
      "500,000 API calls/month",
      "Unlimited integrations",
      "Priority support (4h)",
      "Real-time analytics",
      "API playground access",
      "Webhook support",
      "Team collaboration (5 seats)",
      "99.9% SLA",
      "Custom rate limits",
    ],
    limitations: [],
    cta: "Start Trial",
    popular: true,
  },
  {
    name: "Enterprise",
    tagline: "For mission-critical systems",
    price: { monthly: null, annual: null },
    features: [
      "Unlimited API calls",
      "Unlimited integrations",
      "Dedicated support (1h)",
      "Real-time analytics",
      "Custom API playground",
      "Advanced webhooks",
      "Unlimited team seats",
      "99.99% SLA",
      "Custom rate limits",
      "SOC 2 compliance",
      "Dedicated account manager",
      "On-premise deployment",
    ],
    limitations: [],
    cta: "Contact Sales",
    popular: false,
  },
]

export const dashboardStats = {
  totalCalls: 247893,
  activeApis: 12,
  currentSpend: 156.42,
  avgLatency: 145,
}

export const usageData = [
  { date: "Jan", calls: 12400, errors: 124 },
  { date: "Feb", calls: 18300, errors: 183 },
  { date: "Mar", calls: 24100, errors: 193 },
  { date: "Apr", calls: 31200, errors: 218 },
  { date: "May", calls: 28700, errors: 172 },
  { date: "Jun", calls: 35600, errors: 213 },
  { date: "Jul", calls: 42300, errors: 254 },
  { date: "Aug", calls: 38900, errors: 233 },
  { date: "Sep", calls: 45200, errors: 271 },
  { date: "Oct", calls: 52800, errors: 317 },
  { date: "Nov", calls: 48100, errors: 289 },
  { date: "Dec", calls: 55300, errors: 332 },
]

export const apiByUsage = [
  { name: "OpenAI GPT-4", calls: 89200, percentage: 36 },
  { name: "Stripe Payments", calls: 54300, percentage: 22 },
  { name: "Google Maps", calls: 41700, percentage: 17 },
  { name: "Twilio SMS", calls: 32100, percentage: 13 },
  { name: "Others", calls: 30593, percentage: 12 },
]

export const recentLogs = [
  { timestamp: "2026-02-14 10:23:45", api: "OpenAI GPT-4", endpoint: "/v1/chat/completions", status: 200, latency: "234ms" },
  { timestamp: "2026-02-14 10:23:44", api: "Stripe Payments", endpoint: "/v1/charges", status: 200, latency: "128ms" },
  { timestamp: "2026-02-14 10:23:42", api: "Google Maps", endpoint: "/geocode/json", status: 200, latency: "87ms" },
  { timestamp: "2026-02-14 10:23:40", api: "Twilio SMS", endpoint: "/Messages.json", status: 201, latency: "156ms" },
  { timestamp: "2026-02-14 10:23:38", api: "OpenAI GPT-4", endpoint: "/v1/chat/completions", status: 429, latency: "12ms" },
  { timestamp: "2026-02-14 10:23:35", api: "SendGrid Email", endpoint: "/v3/mail/send", status: 202, latency: "93ms" },
  { timestamp: "2026-02-14 10:23:33", api: "Cloudinary", endpoint: "/v1_1/upload", status: 200, latency: "412ms" },
  { timestamp: "2026-02-14 10:23:30", api: "OpenAI GPT-4", endpoint: "/v1/embeddings", status: 200, latency: "189ms" },
]

export const apiKeys = [
  { id: 1, name: "Production", prefix: "pk_live_...a4f2", created: "2026-01-15", lastUsed: "2026-02-14", status: "active" },
  { id: 2, name: "Staging", prefix: "pk_test_...b7e1", created: "2026-01-20", lastUsed: "2026-02-13", status: "active" },
  { id: 3, name: "Development", prefix: "pk_dev_...c9d3", created: "2026-02-01", lastUsed: "2026-02-14", status: "active" },
  { id: 4, name: "Old Production", prefix: "pk_live_...d1a8", created: "2025-11-10", lastUsed: "2025-12-31", status: "revoked" },
]
